### ISSUE TITLE
[Suggestion] Export variables

### ISSUE THREAD

**Issue by kwrooijen** [arcadia-unity/ArcadiaGodot#24]
Currently the only way (AFAIK) to export variables is to attach a gdscript to the top node and write exports in GDScript. Then in your Clojure file you can use the `.Get` method.

```clojure
(defn ready [self _]
  (.Get self "some_variable"))
```

Ideally we would want to add variables without having to add a GDScript and accessing them through `.Get`.

One option is to provide a `variables.edn` file which contain scenes / export variables. This can be used to generate GDScript files and attach then to the specific scene. We could the unpack these variables in `ArcadiaHooks.cs` and possible put then in the state?

```clojure
{"res://Scenes/Main.tscn"
 {:mob PackedScene}

 "res://Scenes/Player.tscn"
 {:speed int
  :job (String "Warrior" "Magician" "Thief")}

 "res://Scenes/Mob.tscn"
 {:min-speed int
  :max-speed int}}
```

**Comment by selfsame** [comment]
closing this too, see https://github.com/arcadia-unity/ArcadiaGodot/issues/23
