### ISSUE TITLE
[Feature] Initialize boot hook

### ISSUE THREAD

**Issue by kwrooijen** [arcadia-unity/ArcadiaGodot#29]
Currently we need to wait a bit for Arcadia to boot. It would be nice of we could hook into the boot process (probably through a cs script, since Clojure isn't loaded yet). Somewhere here: https://github.com/arcadia-unity/ArcadiaGodot/blob/master/ArcadiaHook.cs#L55-L57

This would be useful so that you can setup a custom splash screen / initial window size.

**Comment by selfsame** [comment]
Understand what you're getting at but at the point you've highlighted I don't believe any Godot API calls would have a visual effect before the thread gets locked up.

The pattern I've used for this is to have the main scene be a splash scene that loads a second scene with an ArcadiaHook

**Comment by kwrooijen** [comment]
That sounds like a pattern that could work for me, thanks
