### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by androclus** [arcadia-unity/ArcadiaGodot#3]
Hey, Tims and Ramsey, et al --

Is this sub-project ArcadiaGodot still alive? Just checking in.. evaluating Unity v Godot, I'd like to work in Clojure, but Godot may be a better fit for the project specs, so I was just wondering..
Thanks!
-A

**Comment by nasser** [comment]
I actually wouldn't know -- that's a @selfsame question. Have you tried the instructions in the README?

**Comment by selfsame** [comment]
Yeah README instructions still work, it's a much more 'bare boned' setup than Arcadia though
