### ISSUE TITLE
Godot language support

### ISSUE THREAD

**Issue by ShalokShalom** [arcadia-unity/ArcadiaGodot#7]
Hi there 🥳 

I am one of the maintainers of the semi-official language support overview for Godot

https://github.com/Vivraan/godot-lang-support

We give all bindings according to their feature set and implementation emoticons to differentiate them. 

So, if they have inbuild-Editor support, if they use the NativeScript, PluginScript or Module API and so on.

Could you hint me, how this is actually integrated?
You have your own, dedicated issue on our project, that will always stay open for suggestions and changes of all sorts.

[Feel welcome](https://github.com/Vivraan/godot-lang-support/issues/29) .

**Comment by selfsame** [comment]
thanks for the inclusion, I've answered some questions over on that thread!
